Delete From Sys_Entity

--set   nocount   on   select   'insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values('as   '--',''''+E_ProgID+'''',',',''''+E_Entity+'''',',',''''+E_Title+'''',')'   from   sys_Entity
--                                                                                                                                                                    
-------------------------------------------------------- ----------------- ---- ---------------------- ---- ---------------------------------------------------- ---- 
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    ''                     ,    '恒基管理系统'                                             )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_A02'             ,    '系统日志'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_B02'             ,    '客户管理'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_B03'             ,    '业务人员'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_B04'             ,    '合同管理'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_D05'             ,    '纸卡查询'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_A06_2'           ,    '磁卡管理'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_C07'             ,    '收据管理'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_L03'             ,    '出入金明细'                                              )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_L02'             ,    '客户账户'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_C01'             ,    '纸卡审核'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_C03'             ,    '信用管理'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'CUSCREDIT'            ,    '信用明细'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_C02'             ,    '货款回收'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_D06'             ,    '提货查询'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_H03'             ,    '门卫查询'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_E03'             ,    '磅房查询'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_F03'             ,    '栈台查询'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_G02'             ,    '放灰查询'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_L01'             ,    '出入车辆'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_L07'             ,    '累计发货'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_L06'             ,    '发货明细'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_L05'             ,    '用户业务'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_D07'             ,    '退购查询'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_L08'             ,    '纸卡明细'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_M01'             ,    '供应商'                                                )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_M02'             ,    '原材料'                                                )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_M03'             ,    '供应磁卡'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_M04'             ,    '供应明细'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_K01'             ,    '品种管理'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_K02'             ,    '检验记录'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_K03'             ,    '开单记录'                                               )
insert   sys_Entity(E_ProgID,E_Entity,E_Title)   values( 'HJSOFT'          ,    'MAIN_F04'             ,    '装车查询'                                               )

